spring.application.name=perfume

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/cicrlgt?currentSchema=perfume
spring.datasource.username=admin
spring.datasource.password=toor
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# LOGGING SQL
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===============================
# JACKSON
# ===============================
spring.jackson.serialization.fail-on-empty-beans=false