spring.application.name=perfume

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE
# ===============================
#spring.datasource.url=jdbc:postgresql://localhost:5432/perfume?currentSchema=aurabgparfum
#spring.datasource.username=postgres
#spring.datasource.password=toor
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/cicrlgt?currentSchema=perfume
spring.datasource.username=postgres
spring.datasource.password=toor
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# LOGGING SQL
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===============================
# JACKSON
# ===============================
spring.jackson.serialization.fail-on-empty-beans=false

# ===============================
# IMAGENES
# ===============================
app.upload.lociones-path=/Users/bagnermerida/logs/Perfume/Lociones
app.upload.lociones-url=/images/lociones

#app.upload.lociones-path=/home/adminpi/logs/Perfume/Lociones
#app.upload.lociones-url=/images/lociones

# ===============================
# JWT
# ===============================
jwt.secret=josK2oxs6iXamqoBzucrZPKaUYclfVYS1mBdUuMBcpHSZ9eLT4zvgEpCKNJUxyI3Wq0dpfwioMCywtrcVz5AZA==
jwt.expiration=86400